Vagrant.configure("2") do |config|
  # Definir una caja base (una imagen de sistema operativo)
  config.vm.box = "bento/ubuntu-24.04"

  # Configurar la máquina virtual
  config.vm.define "ubuntu3" do |ubuntu3|
    ubuntu3.vm.hostname = "ubuntu3"
    ubuntu3.vm.network "private_network", ip: "192.168.100.13"
  end
end
