# Clonación del repositorio con los comandos y recursos desde GitHub
$git_trincheras_docker = <<-SCRIPT
  echo Clonando repositorio 'trincheras-docker' desde GitHub...
  git clone https://github.com/blancazure/trincheras-docker.git
  mkdir /home/vagrant/trincheras-docker/capitulo05/estructura/.directorio-oculto
  chown -R vagrant:vagrant trincheras-docker
SCRIPT

Vagrant.configure("2") do |config|
  # Configuración base para todas las VM
  config.vm.provider "virtualbox" do |vb|
    vb.check_guest_additions = false     
    vb.memory = "2048"
    vb.cpus = 2
    vb.gui = false
  end

  # Establece el tiempo máximo de espera de inicio en 600s
  config.vm.boot_timeout = 600  

  # Desactivar la instalación y actualización de las Guest Additions
  config.vbguest.auto_update = false
  config.vbguest.no_install = true    

  # Se desactivan las carpetas compartidas, no se van a utilizar
  config.vm.synced_folder ".", "/vagrant", disabled: true      

  # Definición de las máquinas
  machines = [
    {name: "ubuntu", ip: "192.168.100.101", ports: 50100..50120, script: "script-ubuntu.sh"},
    {name: "fedora", ip: "192.168.100.102", ports: 50200..50220, script: "script-fedora.sh"},
    {name: "debian", ip: "192.168.100.103", ports: 50300..50320, script: "script-debian.sh"},
    {name: "rocky",  ip: "192.168.100.104", ports: 50400..50420, script: "script-rocky.sh"}
  ]

  # Configuración de cada máquina utilizando un bucle
  machines.each do |machine|
    config.vm.define "vm-lab-docker-#{machine[:name]}" do |vm_config|
      vm_config.vm.box = "blancazure/box-lab-docker-#{machine[:name]}"
      vm_config.vm.box_check_update = true
      vm_config.vm.hostname = "vm-lab-docker-#{machine[:name]}"
      vm_config.vm.network "private_network", ip: machine[:ip]

      machine[:ports].each do |port|
        vm_config.vm.network "forwarded_port", guest: port, host: port
      end

      vm_config.vm.provision "shell", path: "./scripts/#{machine[:script]}"
      vm_config.vm.provision "shell", inline: $git_trincheras_docker

      vm_config.vm.provider "virtualbox" do |v|
        v.name = "vm-lab-docker-#{machine[:name]}"
      end

      vm_config.vm.post_up_message = <<-MESSAGE
        ¡#{machine[:name].capitalize} en marcha! 🐳 La máquina 'vm-lab-docker-#{machine[:name]}' ha sido desplegada correctamente.
      MESSAGE
    end
  end
end
