Vagrant.configure("2") do |config|
  # Definir una caja base (una imagen de sistema operativo)
  config.vm.box = "ubuntu/focal64"

  # Configurar la primera máquina virtual
  config.vm.define "ubuntu1" do |ubuntu1|
    ubuntu1.vm.hostname = "ubuntu1"
    ubuntu1.vm.network "private_network", ip: "192.168.100.11"
  end

  # Configurar la segunda máquina virtual
  config.vm.define "ubuntu2" do |ubuntu2|
    ubuntu2.vm.hostname = "ubuntu2"
    ubuntu2.vm.network "private_network", ip: "192.168.100.12"
  end
end